services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: rails_api
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: ${RAILS_ENV}
      PORT: ${PORT}
    volumes:
      - .:/app
    ports:
      - "3001:${PORT}"
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  postgres_data:
