default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "reimbursement_development" %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "reimbursement_test" %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "reimbursement_production" %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  url: <%= ENV["DATABASE_URL"] %>
